### PR TITLE
Add ands and ors to concrete syntax

### LINKED ISSUE #104: Extend colis with and/or operators on booleans
To improve the readability of generated colis programs, we should avoid the nesting of if-then-else which results from the encoding of or/and operators.

Could we extend colis with these boolean operators?

### PR DESCRIPTION
**Pull request by benozol**
closes #104

### CODE REVIEW

**Comment by claudemarche** [comment]
That's good and already fine for the use of pretty-printing the colis codes generated by morsmall, but theer should also be parsing rules for those `and` and `or`

**Comment by Niols** [comment]
Agreed. It would be nice to have that the parser is always capable of parsing what the pretty-printer outputs.

**Comment by benozol** [comment]
Well - the meaning of the printer output is currently undefined: Any opinions about precedents of AND / OR? What about no precedence and just left-associativity?

**Comment by claudemarche** [comment]
Good point: I suggest to put parentheses in the output, e.g. `[@(%a and@ %a)@]`

For parsing: AND have priority over OR, of course, and I suggest RIGHT associativity for both, not left

**Comment by Niols** [comment]
In Shell, && and || have the same precedence. But it does not necessarilly make sense to have that in Colis.

— Nicolas Jeannerod

**Comment by claudemarche** [comment]
Fine with me now

**Comment by claudemarche** [comment]
Isn't there any choice "rebase and merge when ci succeeds?" too bad...

**Pull request merged**
